"""fixed SectionBids backref

Revision ID: 692859996467
Revises: c7e8864136f9
Create Date: 2019-07-31 14:17:19.835162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692859996467'
down_revision = 'c7e8864136f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'section', ['choice_num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='unique')
    # ### end Alembic commands ###
