"""sections, round 1 bids tables

Revision ID: a6dcf1777c5b
Revises: b255e3b92849
Create Date: 2019-07-12 13:32:02.086839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6dcf1777c5b'
down_revision = 'b255e3b92849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('mon_wed', sa.Boolean(), nullable=True),
    sa.Column('tue_thu', sa.Boolean(), nullable=True),
    sa.Column('mtwth', sa.Boolean(), nullable=True),
    sa.Column('course', sa.String(length=4), nullable=True),
    sa.Column('room', sa.String(length=20), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('bid_1_prep', sa.Integer(), nullable=True),
    sa.Column('bid_2_prep', sa.Integer(), nullable=True),
    sa.Column('bid_3_prep', sa.Integer(), nullable=True),
    sa.Column('bid_4_prep', sa.Integer(), nullable=True),
    sa.Column('bid_5_prep', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bids_timestamp'), 'user_bids', ['timestamp'], unique=False)
    op.create_table('section_bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('user_bids_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['user_bids_id'], ['user_bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_total_bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('userbids_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userbids_id'], ['user_bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_total_bid')
    op.drop_table('section_bid')
    op.drop_index(op.f('ix_user_bids_timestamp'), table_name='user_bids')
    op.drop_table('user_bids')
    op.drop_table('section')
    # ### end Alembic commands ###
