"""updated sections, bids, etc

Revision ID: c7e8864136f9
Revises: a6dcf1777c5b
Create Date: 2019-07-31 13:31:25.489233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e8864136f9'
down_revision = 'a6dcf1777c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_total_bid')
    op.add_column('section', sa.Column('choice_num', sa.Integer(), nullable=True))
    op.add_column('section', sa.Column('semester', sa.String(length=6), nullable=True))
    op.add_column('section', sa.Column('taken_by', sa.String(length=25), nullable=True))
    op.add_column('user_bids', sa.Column('max_acc_units', sa.Integer(), nullable=True))
    op.add_column('user_bids', sa.Column('max_des_units', sa.Integer(), nullable=True))
    op.add_column('user_bids', sa.Column('min_acc_units', sa.Integer(), nullable=True))
    op.add_column('user_bids', sa.Column('min_des_units', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bids', 'min_des_units')
    op.drop_column('user_bids', 'min_acc_units')
    op.drop_column('user_bids', 'max_des_units')
    op.drop_column('user_bids', 'max_acc_units')
    op.drop_column('section', 'taken_by')
    op.drop_column('section', 'semester')
    op.drop_column('section', 'choice_num')
    op.create_table('unit_total_bid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bid', sa.INTEGER(), nullable=True),
    sa.Column('units', sa.INTEGER(), nullable=True),
    sa.Column('userbids_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['userbids_id'], ['user_bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
